# LUXORA asset fetcher — pulls era images/fonts the archive capture didn't hold locally.
# Reads tools/assets-manifest.txt (generated by tools/pageprep.py):
#   kind|remote-url|local-path-under-site/wwwroot
# Tries the live rbxcdn first, then the Wayback Machine, saves into site/wwwroot/...
# Run from the repo root on the VPS:  powershell -ExecutionPolicy Bypass -File tools\fetch-assets.ps1
$ErrorActionPreference = 'Continue'
$repo = Split-Path -Parent $PSScriptRoot
$manifest = Join-Path $repo 'tools\assets-manifest.txt'
if (!(Test-Path $manifest)) { Write-Host "no manifest ($manifest) - nothing to fetch"; exit 0 }

$ok = 0; $fail = 0
foreach ($line in Get-Content $manifest) {
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    $parts = $line.Split('|')
    if ($parts.Count -lt 3) { continue }
    if ($parts.Count -eq 4) { $kind, $remote, $arch, $rel = $parts }
    else { $kind, $remote, $rel = $parts; $arch = 'https://web.archive.org/web/2020im_/' + $remote }
    # Captured tr.rbxcdn URLs expire. Stable place IDs are handled by the dedicated
    # thumbnail-metadata fetcher below instead of retrying dead hash URLs.
    if ($rel -like 'bundles/img/templates/*') { continue }
    $dest = Join-Path (Join-Path $repo 'site\wwwroot') $rel
    if (Test-Path $dest) { $ok++; continue }

    # candidate URLs: live CDN first (+ extensionless twin), then wayback (exact capture ts)
    $cands = @($remote)
    if ($remote -match '^(https://images\.rbxcdn\.com/[0-9a-fA-F]+)\.\w+$') { $cands += $Matches[1] }
    if ($arch) { $cands += $arch }

    New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
    $got = $false
    foreach ($u in $cands) {
        try {
            Invoke-WebRequest -Uri $u -OutFile $dest -TimeoutSec 25 -UseBasicParsing
            if ((Get-Item $dest).Length -gt 50) { $got = $true; break }
            Remove-Item $dest -Force
        } catch { }
    }
    if ($got) { $ok++; Write-Host "OK   $rel" }
    else      { $fail++; Write-Host "FAIL $rel  ($remote)" -ForegroundColor Yellow }
}
Write-Host ""
Write-Host "done: $ok ok, $fail failed. Failed ones are non-fatal (page works without them)." -ForegroundColor Cyan
Write-Host ""
Write-Host "refreshing Create Experience template cards through thumbnail metadata..." -ForegroundColor Cyan
& (Join-Path $PSScriptRoot 'fetch-template-images.ps1')
